// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbMDim2fR8n0O34vc8LBIVKQ74aSV4WNQ',
    appId: '1:560428362228:web:b48fc014ed722ce94bf1a1',
    messagingSenderId: '560428362228',
    projectId: 'cleaning--service--app',
    authDomain: 'cleaning--service--app.firebaseapp.com',
    storageBucket: 'cleaning--service--app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPi5ADVYRBy8dgvwZM8ZyK5I4bIzsEHGY',
    appId: '1:560428362228:android:17f62bc403d91f2a4bf1a1',
    messagingSenderId: '560428362228',
    projectId: 'cleaning--service--app',
    storageBucket: 'cleaning--service--app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDElEG8orUiMZGhnxVcOFlrrAaX3o7bGSA',
    appId: '1:560428362228:ios:2fae3ad3e6f101604bf1a1',
    messagingSenderId: '560428362228',
    projectId: 'cleaning--service--app',
    storageBucket: 'cleaning--service--app.firebasestorage.app',
    iosBundleId: 'com.example.cleaningService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDElEG8orUiMZGhnxVcOFlrrAaX3o7bGSA',
    appId: '1:560428362228:ios:2fae3ad3e6f101604bf1a1',
    messagingSenderId: '560428362228',
    projectId: 'cleaning--service--app',
    storageBucket: 'cleaning--service--app.firebasestorage.app',
    iosBundleId: 'com.example.cleaningService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbMDim2fR8n0O34vc8LBIVKQ74aSV4WNQ',
    appId: '1:560428362228:web:d0e7f4232bc4f4864bf1a1',
    messagingSenderId: '560428362228',
    projectId: 'cleaning--service--app',
    authDomain: 'cleaning--service--app.firebaseapp.com',
    storageBucket: 'cleaning--service--app.firebasestorage.app',
  );
}
